#!/usr/bin/env python3
"""
Create a single-file SVG sprite (bu-covers.svg) from 7 BU cover images.

Usage:
  python3 Website/scripts/make_bu_covers_sprite.py \
    --inbox Website/assets/covers/_bu_inbox \
    --out Website/assets/covers/bu-covers.svg

Inbox must contain:
  dollar.(png|jpg|jpeg|webp)
  penny.(png|jpg|jpeg|webp)
  commemoratives.(png|jpg|jpeg|webp)
  nickel.(png|jpg|jpeg|webp)
  dime.(png|jpg|jpeg|webp)
  quarter.(png|jpg|jpeg|webp)
  half_dollar.(png|jpg|jpeg|webp)

We convert each to PNG 256x256 using `sips`, then embed as base64 data URIs into symbols.
"""

from __future__ import annotations

import argparse
import base64
import subprocess
from pathlib import Path

SECTIONS = [
    ("dollar", "Dollar"),
    ("penny", "Penny"),
    ("commemoratives", "Commemoratives"),
    ("nickel", "Nickel"),
    ("dime", "Dime"),
    ("quarter", "Quarter"),
    ("half_dollar", "Half Dollar"),
]

EXTS = [".png", ".jpg", ".jpeg", ".webp"]


def find_image(inbox: Path, key: str) -> Path | None:
    for ext in EXTS:
        p = inbox / f"{key}{ext}"
        if p.exists():
            return p
    return None


def to_png_256(src: Path, tmp: Path) -> Path:
    tmp.parent.mkdir(parents=True, exist_ok=True)
    # Convert to png
    subprocess.run(["sips", "-s", "format", "png", str(src), "--out", str(tmp)], check=True, stdout=subprocess.DEVNULL)
    # Resize max dimension to 256 (keeps aspect ratio). Our BU images are square already.
    subprocess.run(["sips", "-Z", "256", str(tmp)], check=True, stdout=subprocess.DEVNULL)
    return tmp


def b64_data_uri(png_path: Path) -> str:
    data = png_path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:image/png;base64,{b64}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inbox", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    inbox: Path = args.inbox
    out: Path = args.out
    out.parent.mkdir(parents=True, exist_ok=True)

    missing = []
    entries: list[tuple[str, str]] = []

    tmp_dir = out.parent / ".tmp_bu"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    for key, _label in SECTIONS:
        src = find_image(inbox, key)
        if not src:
            missing.append(key)
            continue
        tmp_png = tmp_dir / f"{key}.png"
        to_png_256(src, tmp_png)
        entries.append((key, b64_data_uri(tmp_png)))

    if missing:
        raise SystemExit(f"Missing BU cover(s) in {inbox}: {', '.join(missing)}")

    # Build the sprite.
    lines = []
    lines.append('<!-- Auto-generated by make_bu_covers_sprite.py -->')
    lines.append('<svg xmlns="http://www.w3.org/2000/svg" style="display:none" viewBox="0 0 256 256">')
    for key, data_uri in entries:
        lines.append(f'  <symbol id="{key}" viewBox="0 0 256 256">')
        lines.append(f'    <image href="{data_uri}" x="0" y="0" width="256" height="256" preserveAspectRatio="xMidYMid meet" />')
        lines.append("  </symbol>")
    lines.append("</svg>")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

